name: Dev - Publish Frontend Docker Image

on:
  push:
    tags:
      - '*.*.*-dev'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      BUBBLES_VERSION: 'dev'
    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v3

      - name: âš™ Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: âš™ Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: âš™ Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: âš™ Set up Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: âš™ Build docker config
        working-directory: ./examples/docker
        run: BUBBLES_VERSION=dev node process.js

      - name: âš™ Install tiptap
        working-directory: ./examples/docker
        run: yarn add @tiptap/pm prosemirror-commands prosemirror-keymap prosemirror-model prosemirror-schema-list prosemirror-state prosemirror-transform prosemirror-view prosemirror-dropcursor prosemirror-gapcursor prosemirror-history

      - name: âš™ Install
        run: yarn install --frozen-lockfile

      - name: ğŸ”§ Build Frontend
        working-directory: ./examples/docker
        run: yarn front:build

      - name: ğŸ”§ğŸš€ Build and push Docker
        uses: docker/build-push-action@v4
        with:
          context: ./examples/docker
          push: true
          tags: leemonade/leemons-front:dev
