name: DEV Publish packages to NPM
on:
  push:
    tags:
      - '*.*.*-mdev'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ›Žï¸ Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: ðŸ”§ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: ðŸ”§ Patch and publish to NPM
        run: >
          NODE_AUTH_TOKEN=${{ secrets.NPM_TOKEN }} bash patch_publish.sh
          ./packages/leemons-academic-portfolio
          ./packages/leemons-cache
          ./packages/leemons-common
          ./packages/leemons-deployment-manager
          ./packages/leemons-emails
          ./packages/leemons-error
          ./packages/leemons-lrn
          ./packages/leemons-menu-builder
          ./packages/leemons-middlewares
          ./packages/leemons-mongodb
          ./packages/leemons-mongodb-helpers
          ./packages/leemons-mqtt
          ./packages/leemons-multi-events
          ./packages/leemons-multilanguage
          ./packages/leemons-permissions
          ./packages/leemons-providers
          ./packages/leemons-react
          ./packages/leemons-runner
          ./packages/leemons-service-name-parser
          ./packages/leemons-testing
          ./packages/leemons-transactions
          ./packages/leemons-users
          ./packages/leemons-utils
          ./packages/leemons-validator
          ./packages/leemons-widgets
          ./packages/leemons-xapi
          dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: ðŸ”§ Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git status | grep "nothing to commit"; then echo "false"; else echo "true"; fi)

      - name: ðŸš€ Git push
        if: steps.git-check.outputs.modified == 'true'
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git fetch origin microservices/dev
          git checkout microservices/dev
          git add .
          git commit -m 'chore: version bump'
          git push origin microservices/dev
